Tommify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('social.urls', namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "social"

urlpatterns = [
    path('',views.home, name='home'),
    path('profile/', views.edit_profile, name="profile_edit"),
    path('network/', views.network, name="network"),
    path('friends/', views.friends_list, name="friends_list"),
    path('like_post/<int:post_id>/', views.like_post, name = 'like_post'),
    path('like_comment/<int:comment_id>/', views.like_comment, name = 'like_comment'),
    path('comment/<int:post_id>/', views.add_comment, name = 'add_comment'),
    path("follow/<int:user_id>/", views.follow_user, name="follow_user"),
    path("unfollow/<int:user_id>/", views.unfollow_user, name="unfollow_user"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name="liked_posts", blank=True)
    following = models.ManyToManyField(User, related_name='post_following', blank=True)
    
    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return f"{self.user.username} - {self.content[:30]}"
        
        
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "user_likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name = "post_likes")
    
    class Meta:
        unique_together = ('post', 'user')
        

        
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "user_comment")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name = "post_comment")
    likes = models.ManyToManyField(User, related_name="liked_comment", blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def total_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return f"{self.user.username}: {self.content[:20]}"
    
class Friendship(models.Model):
    follower = models.ForeignKey(User, related_name= "following" ,on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name="followers", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('follower', 'following')

    def __str__(self):
        return f"{self.follower} follows {self.following}"
        
        
        

social/forms.py
from django import forms
from django.contrib.auth.models import User
from authentication.models import Profile
from .models import Post, Comment


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError("Email already in use")
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio','location','photo']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']
        
        
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

social/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import UserEditForm,ProfileEditForm
from django.contrib import messages
from authentication.models import Profile
from .models import Post, Friendship,User,Like,Comment
from .forms import PostForm, CommentForm

@login_required
def home(request):
    posts = Post.objects.all().order_by("-created_at")
    
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)
   
   
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("social:home")
    else:
        form = PostForm()
    following_ids = Friendship.objects.filter(follower=request.user).values_list("following_id", flat=True)
    people_to_connect = Profile.objects.exclude(user__id__in=following_ids).exclude(user=request.user)
    posts = Post.objects.all().order_by("-created_at")
    users = User.objects.exclude(id=request.user.id)  # Get all other users
    following = list(Friendship.objects.filter(follower=request.user).values_list("following_id", flat=True))
    return render(request, 'homepage.html', {
                    'form':form,
                    'posts':posts,
                    'profile':profile,
                    'people_to_connect':people_to_connect,
                    "users": users,
                    "following": following,
    })

@login_required
def edit_profile(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect('social:profile_edit')
        else:
            messages.error(request, "Error updating your profile.")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=profile)
    return render(request, 'profile.html', {'user_form':user_form, 'profile_form':profile_form, 'profile':profile})

#Connect view section
@login_required
def follow_user(request, user_id):
    user_to_follow = get_object_or_404(User, id=user_id)
    if request.user != user_to_follow:
        Friendship.objects.get_or_create(follower=request.user, following=user_to_follow)
    # Get the 'next' parameter to determine the previous page
    next_page = request.GET.get('next', 'social:home')  # Defaults to 'home' if 'next' isn't provided
    return redirect(next_page)

@login_required
def unfollow_user(request, user_id):
    user_to_unfollow = get_object_or_404(User, id=user_id)
    follow_instance = Friendship.objects.filter(follower=request.user, following=user_to_unfollow)
    if follow_instance.exists():
        follow_instance.delete()
    # Get the 'next' parameter to determine the previous page
    next_page = request.GET.get('next', 'social:home')  # Defaults to 'home' if 'next' isn't provided
    return redirect(next_page)

@login_required
def like_post(request, post_id):
    user = request.user
    post = get_object_or_404(Post, id=post_id)
    if user in post.likes.all():
        post.likes.remove(user)
    else:
        post.likes.add(user)
    return redirect("social:home")
    
@login_required
def like_comment(request, comment_id):
    user = request.user  
    comment = get_object_or_404(Comment, id=comment_id)
    if user in comment.likes.all():
        comment.likes.remove(user)
    else:
        comment.likes.add(user)
    return redirect("social:home")
       
@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('social:home')
    return redirect('social:home')

@login_required
def friends_list(request):
    following_ids = Friendship.objects.filter(follower=request.user).values_list("following_id", flat=True)
    friends = User.objects.filter(id__in=following_ids)  # Get user objects of those being followed
    profile = Profile.objects.get(user=request.user)
    
    friends_with_profiles = []
    for friend in friends:
        friend_profile = Profile.objects.filter(user=friend).first()
        friends_with_profiles.append({"id":friend.id, "user":friend, "profile_image":friend_profile.photo.url if friend_profile and friend_profile.photo else None})
    return render(request, 'friends.html', {'friends': friends, 'friends_with_profiles':friends_with_profiles, 'profile':profile})
    
    
@login_required
def network(request):
    profile = Profile.objects.get(user=request.user)
    following_ids = Friendship.objects.filter(follower=request.user).values_list("following_id", flat=True)
    people_to_connect = Profile.objects.exclude(user__id__in=following_ids).exclude(user=request.user)
    return render(request, 'network.html', {'people_to_connect':people_to_connect, 'profile':profile})

social/templates/friends.html
{% extends 'social_base.html' %}
{% load static %}
{% block friend %}
<div class="col-lg-7 col-12 mx-auto p-3 " >
    <h3 class="text-primary">My Friends</h3>
    <div class="list-group">
        {% for friend in friends_with_profiles %}
        <div class="list-group-item d-flex justify-content-between align-items-center">
            <div>
				{% if friend.profile_image %}
                    <img src="{{friend.profile_image}}" alt="{{ friend.user.username }}" class="rounded-circle me-2 thumbline1" >
                {% else %}
                    <img src="{% static 'img/profile.png' %}" alt="{{ friend.user.username }}" class="rounded-circle me-2 thumbline1" >
                {% endif %}
				<strong>
					{% if friend.user.last_name and friend.user.first_name%}{{friend.user.last_name|title}} {{friend.user.first_name|title}}{% else %}{{friend.user.username|title}}{% endif %}
                </strong>
            </div>
            <a href="{% url 'social:unfollow_user' friend.id %}?next=social:friends_list" class="btn btn-danger btn-sm">Disconnect</a>
        </div>
        {% empty %}
        <p class="text-muted">You have no friends yet.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

social/templates/homepage.html
{% extends 'social_base.html' %}
{% load static %}
{% block main-content %}
<div class="col-lg-7 col-12 mx-auto p-3 custom-width">
                <div class="post-input bg-white p-3 rounded shadow-sm ">
                    <div class="d-flex align-items-center">
                        {% if profile.photo %}
                        <img src="{{profile.photo.url}}" alt="Poster" class="rounded-circle me-2 thumbline2" >
                        {% else %}
                        <img src="{% static 'img/profile.png' %}" alt="Poster" class="rounded-circle me-2 thumbline2">
                        {% endif %}
                        <form  method="post" class="w-100">
                        {% csrf_token %}
                            <div class="input-group">
                                
                                <textarea name="content"  class="form-control rounded shadow-sm me-2" placeholder="Write a post..." required></textarea><br><br>
                                <button type="submit" class="btn btn-primary rounded ">Post</button>
                                
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Posts -->
                {% for post in posts %}      
                <div class="post bg-white p-3 rounded shadow-sm mt-3">
                    <div class="d-flex align-items-center">
                        
                        <img src="{% if post.user.profile.photo %}{{post.user.profile.photo.url}}{% else %}{% static 'img/profile.png' %}{% endif %}" alt="Poster" class="rounded-circle me-2 thumbline1" > 
                        <div class="d-flex flex-column">
                            <strong>{% if post.user.last_name and post.user.first_name%}
                                {{post.user.last_name|title}} {{post.user.first_name|title}}
                                {% else %}{{post.user.username|title}}{% endif %}
                            </strong>
                            <small class="text-muted">{{post.created_at}}</small>
                        </div>
                        
                        {% if post.user != request.user %}
							<form method="POST" action="{% if post.user.id in following %}{% url 'social:unfollow_user' post.user.id %}?next=social:home {% else %}{% url 'social:follow_user' post.user.id %} {% endif %}" class="ms-auto">
								{% csrf_token %}
								<button type="submit" class="btn btn-sm btn-primary ms-auto">
									{% if post.user.id in following %}
										Connected
									{% else %}
										Connect +
									{% endif %}
								</button>
							</form>
						{% endif %}
                    </div>
                    
                    <p class="mt-2">{{post.content}}</p>
                    

                    <!-- Like, Comment, and Share Section -->
                    <div class="d-flex justify-content-between mt-3 border-top pt-2">
					<form action = "{% url 'social:like_post' post.id %}">
					  {% csrf_token %}
                        <button class="btn {% if request.user in post.likes.all %} btn-primary {% else %} btn-light {% endif %} btn-sm like-btn">
                            <i class="bi bi-hand-thumbs-up"></i> Like <span class="like-count">{{post.total_likes}}</span>
                        </button>
					</form>
                        <button class="btn btn-light btn-sm" data-bs-toggle="collapse" data-bs-target="#commentForm{{post.id}}">
                            <i class="bi bi-chat"></i> Comment <span class="comment-count">{{post.post_comment.count}}</span>
                        </button>
						
                        <button class="btn btn-light btn-sm share-btn"> 
                            <i class="bi bi-share"></i> Share
                        </button>
                    </div>

                    <!-- Comment Input Field (Hidden by Default) -->
                    <div class="mt-2 collapse" id="commentForm{{post.id}}" >
					   <form action="{% url 'social:add_comment' post.id %}" method="post" >
					   {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="content" class="form-control rounded shadow-sm me-2 comment-input" placeholder="Write a comment..." required>
                            <button type="submit" class="btn btn-primary rounded add-comment">Comment</button>
                        </div>
					   </form>
                   

                    <!-- More Comments Button -->
                    <button class="btn btn-sm btn-secondary mt-2"  data-bs-toggle="collapse" data-bs-target="#commentSection{{post.id}}">More Comments</button>

                    <!-- View Comments Section (Hidden by Default) -->
                    <ul class="list-unstyled mt-2 collapse" id="commentSection{{post.id}}">
					{% for comment in post.post_comment.all %}
						<li class="border-bottom py-2 comment-item">
						 <div class="d-flex align-items-center">
						 <strong class="me-2">{% if comment.user.last_name and comment.user.first_name%}
                            {{comment.user.last_name|title}} {{comment.user.first_name|title}}
                            {% else %}{{comment.user.username|title}}{% endif %}
                        </strong> : {{comment.content}}
						  <span class="ms-auto d-flex align-items-center gap-2">
						  
							<form action = "{% url 'social:like_comment' comment.id %}" class="m-0">
							  {% csrf_token %}
								<button class="btn {% if request.user in comment.likes.all %} btn-primary {% else %} btn-light {% endif %} btn-sm like-btn">
									<i class="bi bi-hand-thumbs-up"></i> Like <span class="like-count">{{comment.total_likes}}</span>
								</button>
							</form>
							<button class="btn btn-sm reply-btn">Reply</button>
						  </span>
						 </div>
						</li>
					{% empty %}
						<p class="text-muted">No comment yet.</p>
					{% endfor %}
					</ul>
                   
                </div>
                
            </div>
		        
				{% endfor %}<br><br><br>
            
             <!-- People to Connect With -->
            <div class="col-lg-3 d-none d-lg-block p-3 position-fixed" style="top:56px; width:25%; right:0; height:100vh; overflow-y:auto;">
                <h5 class="text-primary">People to Connect With</h5>
                {% for person in people_to_connect %}
                <div class="d-flex align-items-center bg-white p-2 rounded shadow-sm mb-2">
                    <img src="{% if person.photo %}{{person.photo.url}}{% else %}{% static 'img/profile.png' %}{% endif %}" alt="User" class="rounded-circle me-2 thumbline1" >
                    <div class="d-flex w-100 align-items-center">
                        <strong class="me-2">{% if person.user.last_name and person.user.first_name%}
                            {{person.user.last_name|title}} {{person.user.first_name|title}}
                            {% else %}{{person.user.username|title}}{% endif %}
                        </strong>
						{% if person.user != request.user %}
							<form method="POST" action="{% if person.user.id in following %}{% url 'social:unfollow_user' person.user.id %}?next=social:home {% else %}{% url 'social:follow_user' person.user.id %} {% endif %}" class="ms-auto">
								{% csrf_token %}
								<button type="submit" class="btn btn-sm btn-primary ms-auto">
									{% if person.user.id in following %}
										Connected
									{% else %}
										Connect +
									{% endif %}
								</button>
							</form>
						
						{% endif %}
                    </div>
                </div>
                {% endfor %}
                
                
            </div>

        </div>

{% endblock %}

social/templates/network.html
{% extends 'social_base.html' %}
{% load static %}
{% block friend %}
<div class="d-flex justify-content-center w-100">
	<div class= "p-3 bg-white shadow rounded" style="width:90%; max-width:600px;">
    <h5 class="text-primary text-center">People to Connect With</h5>
                {% for person in people_to_connect %}
                <div class="d-flex align-items-center bg-white p-2 rounded shadow-sm mb-2">
                    <img src="{% if person.photo %}{{person.photo.url}}{% else %}{% static 'img/profile.png' %}{% endif %}" alt="User" class="rounded-circle me-2 thumbline1" >
                    <div class="d-flex w-100 align-items-center">
                        <strong class="me-2">{% if person.user.last_name and person.user.first_name%}
                            {{person.user.last_name|title}} {{person.user.first_name|title}}
                            {% else %}{{person.user.username|title}}{% endif %}
                        </strong>
						{% if person.user != request.user %}
							<form method="POST" action="{% if person.user.id in following %}{% url 'social:unfollow_user' person.user.id %}?next=social:home {% else %}{% url 'social:follow_user' person.user.id %}?next=social:network {% endif %}" class="ms-auto">
								{% csrf_token %}
								<button type="submit" class="btn btn-sm btn-primary ms-auto">
									{% if person.user.id in following %}
										Connected
									{% else %}
										Connect +
									{% endif %}
								</button>
							</form>		
						{% endif %}
					</div>
				</div>
				{% endfor %}
	</div>
</div>
{% endblock %}

social/templates/profile.html
{% extends 'social_base.html' %}
{% load static %}
{% block main-content %}
        <!-- Profile Update Form -->
        <div class="col-lg-6 col-12 mx-auto p-3">
            <h3 class="text-primary">Update Profile</h3>
            
            <div class="bg-white p-4 rounded shadow-sm">
                <!-- messages -->
                <div class=" text-center w-100 px-3" >
                    {% if messages %}
                    <div class="messages.container">
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                            <div class="alert alert-danger">
                                <a>{{message}}</a>
                            </div>
                            {% elif message.tags == 'success' %}
                            <div class="alert alert-success">
                                <a>{{message}}</a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                </div>
                <form id="profileUpdateForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Profile Picture -->
                    <div class="text-center mb-3">
                        {% if profile.photo %}
                        <img src="{{profile.photo.url}}" alt="Poster" class="rounded-circle me-2 thumbline3" >
                        {% else %}
                        <img src="{% static 'img/profile.png' %}" alt="Poster" class="rounded-circle me-2 thumbline3" >
                        {% endif %}
                        <input type="file" class="form-control mt-2" id="profilePic" name="photo" value="{{profile_form.photo.value}}" accept="image/*">
                    </div>

                    <!-- Username -->
                    <div class="mb-3">
                        <label for="firstname" class="form-label">First name</label>
                        <input type="text" class="form-control" id="firstname" name="first_name" value="{{user_form.first_name.value}}" placeholder="Enter your first name">
                    </div>

                    <div class="mb-3">
                        <label for="lastname" class="form-label">Last name</label>
                        <input type="text" class="form-control" id="lastname" name="last_name" value="{{user_form.last_name.value}}" placeholder="Enter your last name">
                    </div>

                    <!-- Email -->
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{user_form.email.value}}" placeholder="Enter your email">
                    </div>

                    <!-- Bio -->
                    <div class="mb-3">
                        <label for="bio" class="form-label">Bio</label>
                        <textarea class="form-control" id="bio" rows="3" name="bio" placeholder="Tell us about yourself">{{profile_form.bio.value}}</textarea>
                    </div>

                    <!-- Location -->
                    <div class="mb-3">
                        <label for="location" class="form-label">Location</label>
                        <input type="text" class="form-control" id="location" name="location" value="{{profile_form.location.value}}" placeholder="Enter your location">
                    </div>
                    

                    <!-- Save Button -->
                    <button type="submit" class="btn btn-primary w-100">Save Changes</button>
                </form>
            </div>
        </div>

{% endblock %}

social/templates/social_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tommify - Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
   
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> 
</head>
<body class="bg-light">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-primary text-white fixed-top px-3">
        <div class="container-fluid">
            <!-- Sidebar Toggle Button (Only Visible on Mobile) -->
            <button class="btn text-white d-lg-none" data-bs-toggle="offcanvas" data-bs-target="#mobileSidebar">
                <i class="bi bi-list"></i>
            </button>
            <a class="navbar-brand text-white fw-bold fs-6 mb-0 h1 ms-n3" href="#">Tommify</a>

            <div class="d-none d-lg-flex custom-shift">
                <a href="{% url 'social:home' %}" class="mx-2 text-white text-decoration-none">Home</a>
                <a href="{% url 'social:profile_edit' %}" class="mx-2 text-white text-decoration-none">Profile</a>
                <a href="#" class="mx-2 text-white text-decoration-none">Messages</a>
                <a href="#" class="mx-2 text-white text-decoration-none">Notifications</a>
                <a href="#" class="mx-2 text-white text-decoration-none">Groups</a>
                <a href="{% url 'social:friends_list' %}" class="mx-2 text-white text-decoration-none">Friends</a>
            </div>

            <div class="d-lg-none mx-auto d-flex align-items-center ms-n3">
                <a href="{% url 'social:home' %}" class="mx-1 text-white text-decoration-none" data-bs-toggle="tooltip" title="Home"><i class="bi bi-house text-white mx-1"></i></a>
				<a href="{% url 'social:profile_edit' %}" class="mx-1 text-white text-decoration-none" data-bs-toggle="tooltip" title="Profile"><i class="bi bi-person text-white mx-1"></i></a>
                <a href="#" class="mx-1 text-white text-decoration-none" data-bs-toggle="tooltip" title="Messages"><i class="bi bi-chat text-white mx-1"></i></a>
				<a href="#" class="mx-1 text-white text-decoration-none"data-bs-toggle="tooltip" title="Notifications"><i class="bi bi-bell text-white mx-1"></i></a>
				<a href="{% url 'social:friends_list' %}" class="mx-1 text-white text-decoration-none" data-bs-toggle="tooltip" title="Friends"><i class="bi bi-person text-white mx-1"></i></a>
                <i class="bi bi-search text-white d-lg-none mx-1"></i>
            </div>

            <div class="d-flex justify-content-center w-25 d-none d-lg-block mx-3">
				<div class="input-group" style="width: 90%;">
					<input type="text" class="form-control rounded-start shadow-sm" 
						placeholder="Search" style="width: 80%;">
					<span class="input-group-text bg-white border-left-0 ps-3">
						<i class="bi bi-search"></i>
					</span>
				</div>
			</div>
            
            <a class="btn btn-outline-light btn-sm py-1 px-2" href="{% url 'logout' %}">Logout</a>
        </div>
    </nav>

    <!-- Sidebar for Mobile (Offcanvas Sidebar) -->
    <div class="offcanvas offcanvas-start w-50 sidebar-glass " tabindex="-1" id="mobileSidebar">
        <div class="offcanvas-header bg-primary text-white">
            <h5 class="offcanvas-title">Menu</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"></button>
        </div>
        <div class="offcanvas-body text-center">
            {% if profile.photo %}
            <img src="{{profile.photo.url}}" alt="Poster" class="rounded-circle me-2 thumbline1" >
            {% else %}
            <img src="{% static 'img/profile.png' %}" alt="Poster" class="rounded-circle me-2 thumbline1" >
            {% endif %}  
            <a href="{% url 'social:home' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Home</a>
            <a href="{% url 'social:profile_edit' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Profile</a>
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Messages</a>
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Notifications</a>
			<a href="{% url 'social:network' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Network</a>
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Groups</a>
            <a href="{% url 'social:friends_list' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Friends</a>
		{% if user.is_authenticated and user.is_staff %}
			<a href="{% url 'admin:index' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Admin Panel</a>
		{% endif %}
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Settings</a>
            <a href="#" class="d-block text-danger text-decoration-none mt-3 sidebar-link">Logout</a>
        </div>
    </div>

    <!-- Main Content -->
    <div class="container-fluid" style="margin-top:80px;">
        <div class="row">

        <!-- Desktop Sidebar -->
        <div class="col-lg-2 sidebar-glass text-dark text-center vh-100 d-none d-lg-block p-3 sidebar-glass position-fixed" style="top:56px; left:0; width:19%; margin-right:-15px;">
            {% if profile.photo %}
                <img src="{{profile.photo.url}}" alt="Poster" class="rounded-circle me-2 thumbline1" >
           {% else %}
                <img src="{% static 'img/profile.png' %}" alt="Poster" class="rounded-circle me-2 thumbline1" >
            {% endif %}
            
            <a href="{% url 'social:home' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Home</a>
            <a href="{% url 'social:profile_edit' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Profile</a>
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Messages</a>
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Notifications</a>
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Groups</a>
            <a href="{% url 'social:friends_list' %}" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Friends</a>
            <a href="#" class="d-block text-dark text-decoration-none mb-2 sidebar-link">Settings</a>
            <a href="{% url 'logout' %}" class="d-block text-danger text-decoration-none mt-3 sidebar-link">Logout</a>
        </div>

            <!-- Main Content -->
			{% block main-content %}{% endblock %}
			{% block friend %}{% endblock %}
			
        </div>
    </div>
    <!-- Bootstrap JS (for Offcanvas to work) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- <script src="{% static 'js/scripts.js' %}"></script> -->
</body>
</html>